### ISSUE TITLE
Install fails on Fedora 20 via npm

### ISSUE THREAD

**Issue by Piratmac** [prey/prey-node-client#51]
Hello,

I have tried installing prey through "npm -g install prey" on a brand new installation of Fedora 20 (uname -r gives 3.17.4-200.fc20.x86_64.)
I get a sery of error messages, and the program doesn't get installed.

Could you look into this issue?

Thanks!
Piratmac

Please find below the end of the log:

```
npm http 200 https://registry.npmjs.org/traverse/-/traverse-0.3.9.tgz
/bin/prey -> /lib/node_modules/prey/bin/prey

> prey@1.3.3 postinstall /lib/node_modules/prey
> ./bin/prey config hooks post_install

Creating user prey...
prey user already exists!
prey already seems to have impersonation privileges. Skipping...
Creating config dir: /etc/prey
Touching log file: /var/log/prey.log
Setting permissions on /usr/lib/node_modules/prey
Setting permissions on /etc/prey
Setting permissions on /var/log/prey.log
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/node_modules/prey/prey.conf.default
No versions support.
Voila! All good.
--
Installing init scripts.
EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

> prey@1.3.3 preuninstall /lib/node_modules/prey
> ./bin/prey config hooks pre_uninstall

EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
npm WARN continuing anyway undefined
npm ERR! weird error 1
npm ERR! not ok code 0
```

**Comment by cookieofbliss** [comment]
Still doesn't work on Fedora 21 3.17.8-300.fc21.x86_64

--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/node_modules/prey/prey.conf.default
No versions support.
Setting permissions on /usr/lib/node_modules/prey
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

> prey@1.3.6 preuninstall /usr/lib/node_modules/prey
> ./bin/prey config hooks pre_uninstall

EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)
npm WARN continuing anyway undefined
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by lemavri** [comment]
Thanks for your report @cookieofbliss, we'll look into it.

**Comment by xmodulo** [comment]
Same problem on Fedora 21.  It's been a while, and still no update?

**Comment by Piratmac** [comment]
Hello,

I confirm the bug is still there on Fedora 24 (kernel 4.4.8-300.fc23.x86_64)

Regards,
Piratmac

Extract of log:

Setting permissions on /etc/prey
chowning /etc/prey/prey.conf to uid 983 and gid 976
chowning /etc/prey to uid 983 and gid 976
Setting permissions on /var/log/prey.log
chowning /var/log/prey.log to uid 983 and gid 976
Running "config activate" as prey
--
Ensuring presence of config dir: /etc/prey
Syncing /etc/prey/prey.conf with /usr/lib/node_modules/prey/prey.conf.default
No versions support.
Setting permissions on /usr/lib/node_modules/prey
Running post_activate hooks...
Voila! All good.
--
Installing init scripts.
EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/satan/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

> prey@1.3.9 preuninstall /usr/lib/node_modules/prey
> ./bin/prey config hooks pre_uninstall

EXCEPTION! object is not a function
TypeError: object is not a function
    at /usr/lib/node_modules/prey/node_modules/satan/node_modules/linus/index.js:19:14
    at ChildProcess.exithandler (child_process.js:656:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
npm WARN continuing anyway undefined
npm ERR! weird error 1
npm ERR! not ok code 0

**Comment by injcristianrojas** [comment]
Bug confirmed in Fedora 25 also.
